[2025-06-28T05:26:55.326+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_snowflake_dag.log_snowflake_database manual__2025-06-28T05:26:54.387311+00:00 [queued]>
[2025-06-28T05:26:55.331+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_snowflake_dag.log_snowflake_database manual__2025-06-28T05:26:54.387311+00:00 [queued]>
[2025-06-28T05:26:55.331+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-28T05:26:55.340+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): log_snowflake_database> on 2025-06-28 05:26:54.387311+00:00
[2025-06-28T05:26:55.344+0000] {standard_task_runner.py:60} INFO - Started process 202 to run task
[2025-06-28T05:26:55.345+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'simple_snowflake_dag', 'log_snowflake_database', 'manual__2025-06-28T05:26:54.387311+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/snowflake_simple_dag.py', '--cfg-path', '/tmp/tmpxu9inn_3']
[2025-06-28T05:26:55.346+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask log_snowflake_database
[2025-06-28T05:26:55.355+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-28T05:26:55.375+0000] {task_command.py:423} INFO - Running <TaskInstance: simple_snowflake_dag.log_snowflake_database manual__2025-06-28T05:26:54.387311+00:00 [running]> on host 50055f242060
[2025-06-28T05:26:55.448+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_snowflake_dag' AIRFLOW_CTX_TASK_ID='log_snowflake_database' AIRFLOW_CTX_EXECUTION_DATE='2025-06-28T05:26:54.387311+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-28T05:26:54.387311+00:00'
[2025-06-28T05:26:55.456+0000] {base.py:83} INFO - Using connection ID 'my_snowflake_conn' for task execution.
[2025-06-28T05:26:55.457+0000] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.8.18, Platform: Linux-6.2.0-26-generic-x86_64-with-glibc2.34
[2025-06-28T05:26:55.457+0000] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-06-28T05:26:57.377+0000] {cursor.py:1028} INFO - query: [SELECT CURRENT_DATABASE();]
[2025-06-28T05:26:57.681+0000] {cursor.py:1041} INFO - query execution done
[2025-06-28T05:26:57.682+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2025-06-28T05:26:57.682+0000] {logging_mixin.py:188} INFO - âœ… Current Snowflake database is: AIRFLOW_PRACTICE
[2025-06-28T05:26:57.682+0000] {connection.py:718} INFO - closed
[2025-06-28T05:26:57.782+0000] {connection.py:724} INFO - No async queries seem to be running, deleting session
[2025-06-28T05:26:57.888+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-28T05:26:57.900+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=simple_snowflake_dag, task_id=log_snowflake_database, execution_date=20250628T052654, start_date=20250628T052655, end_date=20250628T052657
[2025-06-28T05:26:57.931+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-28T05:26:57.954+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
